title: "Critical Making Portfolio"
description: "A simple portfolio site for class"
baseurl: "/critical-making-portfolio"
url: "https://cestinnett.github.io"
remote_theme: "mmistakes/so-simple-theme"

plugins:
  - jekyll-remote-theme # Required for GitHub Pages
  - jekyll-seo-tag
  # Include custom CSS
include:
  - assets/css/custom.css