title: "Critical Making Portfolio"
description: "A simple portfolio site for class"
baseurl: "/critical-making-portfolio"  # Important for GitHub Pages
url: "https://cestinnett.github.io"
theme: "so-simple-theme"